#-------------------------------
# General Site Settings
title: Bewerbung FH Johanneum
logo: logo.svg # You can add own logo.
description: Bewerbung für ein Master-Studium an der FH Johanneum


#-------------------------------
# Author Settings
author:
  name: Marcus Meindel
  image: profile.jpg
  say-hello: <strong>Marcus Sperber</strong>
  bio: Vor zehn Jahren schloss ich mein BA-Studium mit der Arbeit 'Die Konstruktion einer Erinnerung – Informationsvermittlung im narrativen Film auf das episodische Gedächtnis' ab. Film ist für mich mehr als Unterhaltung und es waren zehn arbeitsreiche Jahre, um besser verstehen zu lernen, wie <strong>Filmproduktion von Grund auf neu gedacht werden kann</strong>. 


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: emze77 # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
